# Change these first
owner: DjonysDalmy # Your GitHub organization or username, where this repository lives
repo:
  status-ibrep
  # The name of this repository

sites:
  - name: Site IBREP
    url: https://www.ibrep.com.br
  - name: Oráculo IBREP - Aluno
    url: https://ibrep.alfamaoraculo.com.br/aluno/
  - name: Oráculo IBREP - Gestor
    url: https://ibrep.alfamaoraculo.com.br/gestor/
  - name: Site IBREPTRAN
    url: https://www.ibreptran.ibrep.com.br
  - name: Oráculo IBREPTRAN - Aluno
    url: https://ibreptran.alfamaoraculo.com.br/aluno/
  - name: Oráculo IBREPTRAN - Gestor
    url: https://ibreptran.alfamaoraculo.com.br/gestor/
  - name: Site ICETRAN
    url: https://www.icetran.com.br
  - name: Loja ICETRAN
    url: https://eadicetran.com.br/painel/
  - name: Oráculo ICETRAN - Aluno
    url: https://icetran.alfamaoraculo.com.br/aluno/
  - name: Oráculo ICETRAN - Gestor
    url: https://icetran.alfamaoraculo.com.br/gestor/

status-website:
  baseUrl: /status-ibrep
  name: Status
  navbar:
    - title: Status
      href: /
