# Change these first
owner: DjonysDalmy # Your GitHub organization or username, where this repository lives
repo:
  status-ibrep
  # The name of this repository

sites:
  - name: Site IBREP
    url: https://ibrep.com.br
    icon: https://app.ibrep.com.br/techdesk/icon/IBREP.png
  - name: API Site IBREP
    url: https://ibrep.com.br/api/ibrep/public/index.php/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREP.png
  - name: APP IBREP
    url: https://app.ibrep.com.br
    icon: https://app.ibrep.com.br/techdesk/icon/IBREP.png
  - name: Oráculo IBREP - Aluno
    url: https://ibrep.alfamaoraculo.com.br/aluno/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREP.png
  - name: Oráculo IBREP - Gestor
    url: https://ibrep.alfamaoraculo.com.br/gestor/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREP.png
  - name: Site IBREPTRAN
    url: https://ibreptran.ibrep.com.br/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREPTRAN.png
  - name: Oráculo IBREPTRAN - Aluno
    url: https://ibreptran.alfamaoraculo.com.br/aluno/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREPTRAN.png
  - name: Oráculo IBREPTRAN - Gestor
    url: https://ibreptran.alfamaoraculo.com.br/gestor/
    icon: https://app.ibrep.com.br/techdesk/icon/IBREPTRAN.png
  - name: Site ICETRAN
    url: https://icetran.com.br
    icon: https://app.ibrep.com.br/techdesk/icon/ICETRAN.png
  - name: Oráculo ICETRAN - Aluno
    url: https://icetran.alfamaoraculo.com.br/aluno/
    icon: https://app.ibrep.com.br/techdesk/icon/ICETRAN.png
  - name: Oráculo ICETRAN - Gestor
    url: https://icetran.alfamaoraculo.com.br/gestor/
    icon: https://app.ibrep.com.br/techdesk/icon/ICETRAN.png
  - name: API Detran RS
    url: https://mgfc.detran.rs.gov.br/gfc/rest/gfcmobile/cursoEAD/validaAluno
    __dangerous__insecure: true
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ }'
    expectedStatusCodes:
      - 403
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Bandeira_do_Rio_Grande_do_Sul.svg/150px-Bandeira_do_Rio_Grande_do_Sul.svg.png

status-website:
  baseUrl: /status-ibrep
  #cname: status.ibrep.com.br # Custom domain CNAME
  name: Status
  theme: night
  introMessage: Essa página realiza requisições para diveros serviços e disponibiliza em tempo real o status dessas aplicações. Confira o status de outros serviçoes que podem ser do seu interesse -> [Slack](https://status.slack.com/) [Google Workspace](https://www.google.com/appsstatus/dashboard/) [Google Cloud](https://status.cloud.google.com/) [AWS](https://status.aws.amazon.com/) [Zoom](https://status.zoom.us/) [Azure](https://status.azure.com/pt-br/status) [Facebook](https://status.fb.com/) [Outros...](https://downdetector.com.br/)


i18n:
  activeIncidents: Erros em andamento
  allSystemsOperational: Todos os Sistemas em operação
  incidentReport: "Erro #$NUMBER reportado →"
  activeIncidentSummary: Aberto às $DATE com $POSTS erros
  incidentTitle: Erro $NUMBER Detalhes
  incidentDetails: Erro Detalhes
  incidentFixed: Resolvido
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto às
  incidentClosedAt: Fechado às
  incidentSubscribe: Se inscreva para atualizações
  incidentViewOnGitHub: Ver no GitHub
  incidentCommentSummary: Postado às $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os erros
  pastIncidents: Erros anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS erros
  liveStatus: Status ao Vivo
  overallUptime: "uptime geral: $UPTIME"
  overallUptimeTitle: uptime geral
  averageResponseTime: "Tempo de resposta médio: $TIMEms"
  averageResponseTimeTitle: Tempo de resposta médio
  sevelDayResponseTime: Tempo de resposta de 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Ok
  down: Fora do ar
  degraded: Inacessível
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: Powered by IBREPTEC
  errorTitle: Um erro ocorreu
  errorIntro: Ocorreu um erro ao tentar obter os detalhes de status mais recentes.
  errorText: Você pode tentar novamente em alguns instantes.
  errorHome: Voltar para Home
  pastScheduledMaintenance: Manutenção programada anterior
  scheduledMaintenance: Manutenção agendada
  scheduledMaintenanceSummaryStarted: Iniciado às $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Iniciado às $DATE por $DURATION minutos
  startedAt: Iniciado às
  startsAt: Inicia às
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Completo
  incidentScheduled: Agendado
